# Generated by Django 5.0.6 on 2024-07-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='metro',
            new_name='address',
        ),
    ]
