# Generated by Django 5.0.6 on 2024-07-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='metro',
            new_name='address',
        ),
    ]
