# Generated by Django 5.0.6 on 2024-07-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_link_alter_savedjob_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
