# Используем базовый образ Python
FROM python:3.10-slim

# Установка зависимостей для PostgreSQL и другие необходимые пакеты
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-server-dev-all \
        gcc \
        python3-dev \
        musl-dev \
    && rm -rf /var/lib/apt/lists/*

# Установка рабочей директории в /app
WORKDIR /app

# Копирование файлов requirements.txt в контейнер
COPY requirements.txt .

# Установка зависимостей из requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копирование остальных файлов проекта в контейнер
COPY . .

# Определение параметров для парсера
ENV PARSE_INTERVAL=43200

# Команда для запуска парсера
CMD ["python", "parser/parser.py"]
