# Используем базовый образ Python
FROM python:3.9

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем requirements.txt и устанавливаем зависимости
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . /app/

# Устанавливаем зависимости для тестирования
RUN pip install pytest pytest-django

# Устанавливаем необходимые переменные окружения
ENV PYTHONUNBUFFERED 1

# Команда по умолчанию для запуска тестов
CMD ["pytest"]
