FROM python:3.10-slim

# Установите зависимости для PostgreSQL и другие необходимые пакеты
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-server-dev-all \
        gcc \
        python3-dev \
        musl-dev \
    && rm -rf /var/lib/apt/lists/*

# Установите рабочую директорию в /app
WORKDIR /app

# Скопируйте файлы requirements.txt в контейнер
COPY requirements.txt .

# Установите зависимости из requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Скопируйте оставшиеся файлы проекта в контейнер
COPY . .

# Откройте порт 8000 для доступа к приложению
EXPOSE 8000

# Запустите сервер Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
