version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hfnfneq2005
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=vacancies
      - DB_USER=postgres
      - DB_PASSWORD=Hfnfneq2005
      - DB_HOST=db
      - DB_PORT=5432

  parser:
    build: .
    command: python parser/parser.py
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=vacancies
      - DB_USER=postgres
      - DB_PASSWORD=Hfnfneq2005
      - DB_HOST=db
      - DB_PORT=5432
      - PARSE_INTERVAL=43200

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=vacancies
      - DB_USER=postgres
      - DB_PASSWORD=Hfnfneq2005
      - DB_HOST=db
      - DB_PORT=5432
